/**
* Catalog
* Catalog
*
* OpenAPI spec version: 1.0.0
* Contact: dev@gb.ru
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.server.models


/**
 * 
 * @param isbn 
 * @param name 
 * @param url 
 * @param author 
 * @param price 
 */
data class Book (
    val isbn: kotlin.String? = null,
    val name: kotlin.String? = null,
    val url: kotlin.String? = null,
    val author: kotlin.String? = null,
    val price: kotlin.Float? = null
) {

}

